/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.ConexaoEntrega;
import classes.Entrega;
import classes.Estoque;
import classes.ListaMateriais;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author cirol
 */
public class listarEntregas extends javax.swing.JFrame {

    ListaMateriais lista = new ListaMateriais();
    private final List<Entrega> listaEnt = ListaMateriais.listarEnt();
    private final List<Estoque> listaEst = ListaMateriais.listarEst();
    ArrayList<Integer> numeros = new ArrayList<>();
    alteraEntregas altera;

    /**
     * Creates new form listarEntregas
     */
    public listarEntregas() {
        initComponents();
        
        Excluir.setEnabled(false);
        Alterar.setEnabled(false);
        Recebido.setEnabled(false);
        int i = 0;
        preencherTabelaCad("");
        while (tabelaList.getRowCount() > i) {
            String idStr = String.valueOf(tabelaList.getValueAt(i, 0));
            int id = Integer.parseInt(idStr);
            numeros.add(id);
            i++;
        }
        tabelaList.removeColumn(tabelaList.getColumnModel().getColumn(0));
    }

    private void preencherTabelaCad(String filtro) {
        ConexaoEntrega con = new ConexaoEntrega();
        boolean status = con.conectar();

        if (status == false) {
            JOptionPane.showMessageDialog(null, "Não foi possível fazer a conexão");
        } else {
            List<Entrega> listaEnt = con.listagemEnt(filtro);
            DefaultTableModel tabelaCadastro = (DefaultTableModel) tabelaList.getModel();
            tabelaList.setRowSorter(new TableRowSorter(tabelaCadastro));

            tabelaCadastro.setNumRows(0);
            for (Entrega f : listaEnt) {
                Object[] obj = new Object[]{
                    f.getId(),
                    f.getDescricaoEnt(),
                    f.getQuantidade(),
                    new SimpleDateFormat("dd/MM/yyyy").format(f.getRecebimento().getTime()),
                    f.getObra()
                };
                tabelaCadastro.addRow(obj);

            }
            con.desconectar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Recebido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaList = new javax.swing.JTable();
        Excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Recebido.setBackground(new java.awt.Color(0, 0, 102));
        Recebido.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Recebido.setForeground(new java.awt.Color(255, 255, 255));
        Recebido.setText("Recebido");
        Recebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebidoActionPerformed(evt);
            }
        });

        tabelaList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id do Produto", "Descrição do Produto", "Quantidade", "Data da Entrega", "Local da Entrega "
            }
        ));
        tabelaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaList);

        Excluir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("Lista de Entregas");

        Voltar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Voltar.setText("<");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Alterar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Alterar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(Excluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Recebido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(Voltar)
                                .addGap(15, 15, 15)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(Alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recebido)
                    .addComponent(Excluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void RecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebidoActionPerformed
        Entrega ent = new Entrega();
        ConexaoEntrega con = new ConexaoEntrega();
        boolean status;
        int resposta;
        int linha = tabelaList.getSelectedRow();
        String produto = String.valueOf(tabelaList.getValueAt(linha, 0));
        String obra = String.valueOf(tabelaList.getValueAt(linha, 3));
        Double quantEnt = Double.parseDouble(String.valueOf(tabelaList.getValueAt(linha, 1)));

        status = con.conectar();
        if (status == false) {
            System.out.println("CATAPIMBAS");
        } else {
            resposta = con.receber(produto, quantEnt, obra);
            int id = numeros.get(linha);

            if (resposta == 1) {
                boolean operacao = con.excluir(id);
                Excluir.setEnabled(false);
                Alterar.setEnabled(false);
                Recebido.setEnabled(false);
                preencherTabelaCad("");
            } else {
                JOptionPane.showMessageDialog(null, "Erro");
            }
        }
        con.desconectar();
    }//GEN-LAST:event_RecebidoActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        ConexaoEntrega con = new ConexaoEntrega();
        boolean status = con.conectar();

        if (status == false) {
            JOptionPane.showMessageDialog(null, "Verifique sua conexão");
        } else {

            int linha = tabelaList.getSelectedRow();
            int id = numeros.get(linha);
            boolean operacao = con.excluir(id);
            if (operacao == true) {

                Excluir.setEnabled(false);
                Alterar.setEnabled(false);
                Recebido.setEnabled(false);
                preencherTabelaCad("");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível realizar a exclusão");
            }
            con.desconectar();
        }
    }//GEN-LAST:event_ExcluirActionPerformed


    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        menuPrincipal menu = new menuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void tabelaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaListMouseClicked
        int linha = tabelaList.getSelectedRow();
        int id = numeros.get(linha);
        Excluir.setEnabled(true);
        Alterar.setEnabled(true);
        Recebido.setEnabled(true);
        //JOptionPane.showMessageDialog(null, id);
        String nome = String.valueOf(tabelaList.getValueAt(linha, 0));

    }//GEN-LAST:event_tabelaListMouseClicked

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        int linha = tabelaList.getSelectedRow();
        String produto = String.valueOf(tabelaList.getValueAt(linha, 0));
        double quantidade = Double.parseDouble(String.valueOf(tabelaList.getValueAt(linha, 1)));
        String data = String.valueOf(tabelaList.getValueAt(linha, 2));
        String obra = String.valueOf(tabelaList.getValueAt(linha, 3));
        int id = numeros.get(linha);
        //System.out.println("Data convertida: " + date);
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, data);
        } else {
            if (altera == null) {
                altera = new alteraEntregas();
                altera.setVisible(true);
                altera.recebendo(quantidade, data, produto, obra, id);
                dispose();
            } else {
                altera.setVisible(true);
                altera.setState(alteraEntregas.NORMAL);
                altera.recebendo(quantidade, data, produto, obra, id);
                dispose();
            }
        }
    }//GEN-LAST:event_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarEntregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarEntregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarEntregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarEntregas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarEntregas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Recebido;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaList;
    // End of variables declaration//GEN-END:variables
}
